[package]
name = "pathfinding-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flamegraph = "0.6.4"
plotters = "0.3.5"
rand = "0.8.5"
serde_json = "1.0.111"

[profile.release]
debug = true
